export const UPSERT_SHOPPING_LIST_ITEMS_PAGINATION_LIMIT = 100;
export const UPDATE_SHOPPING_LIST_ITEMS_PAGINATION_LIMIT = 100;
export const DELETE_SHOPPING_LIST_ITEMS_PAGINATION_LIMIT = 1000;
export const CREATE_SHOPPING_LIST_ITEMS_PAGINATION_LIMIT = 1000;
export const SHOPPING_LIST_TITLE_LENGTH_LIMIT = 254;
export const SHOPPING_LIST_ITEMS_TITLE_LENGTH_LIMIT = 254;
export const SHOPPING_LIST_CATEGORY_ORDER_LENGTH_LIMIT = 10000;
